name: Scheduled Python Worker

on:
  schedule:
    - cron: "12 19 2 * *" # 每天 UTC 时间 19:12 运行(北京时间凌晨3:12)运行 
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Install prerequisites
        run: uv sync --all-extras --dev

      - name: Run Python Script
        run: uv run src/main.py

      - name: tar js file for Windows Client
        run: tar -cJf dist/plugins.tar.xz dist/*.js

      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update plugins.json"
          git push
